[] テキストに URL が含まれていたらリンク化してほしい
EeeeG-Inc/OKR-web-app pull request #155
Opened 2023-10-16 09:09 UTC by ShutaTanaka

本日作業分
コメントがURL化したことは確認できた。
コメントに複数URLがあった場合などは未確認。

2023-10-16 09:29 UTC, Takuma-Ikeda requested changes

2023-10-16 09:29 UTC, Takuma-Ikeda commented on app/Models/Comment.php
> +    public function getCommentAttribute($value)
`getCommentAttribute` ではなく `getLinkedCommentAttribute` などで取得できるようにしてください。
そうすると `$モデル->linked_comment` でアクセスできるはずです。
※ `getCommentAttribute` だと `$モデル->comment` でアクセスすることになるので、元のアトリビュートとコンフリクトしています。

また、引数 `$value` いらないです！
Comment モデルが持つ `comment` アトリビュートは `$this->comment` で利用できますので、
これに正規表現チェックをかけて return してください。

2023-10-16 09:29 UTC, Takuma-Ikeda commented on app/Models/Comment.php
> +    public function getCommentAttribute($value)
戻り値は string を設定して、PHPDoc も修正をお願いします！

2023-10-16 09:29 UTC, Takuma-Ikeda commented on app/Models/Comment.php
> +        $texts = explode(PHP_EOL, $value);
なので `$value` じゃなくて `$this->comment` を使うことになります。

2023-10-16 09:32 UTC, Takuma-Ikeda commented
@ShutaTanaka 
CircleCI の静的解析で文法エラーを吐いてるのでご対応よろしくお願いします。

2023-10-17 04:43 UTC, ShutaTanaka commented
ひとまず、指摘の修正
以下はこれから対応
- URLが複数含まれていた場合、最後のURLのみリンク化されのこりはされない症状が出ている。
- コメント以外にもリンク化が必要な箇所に反映させる。

2023-10-17 05:23 UTC, Takuma-Ikeda requested changes

2023-10-17 05:23 UTC, Takuma-Ikeda commented on app/Models/Comment.php
> +        //PHP_EOLは,改行コードをあらわす.改行があれば分割する
初歩的な文法のことしか書いていないので、コメントは全部消しちゃって大丈夫です

2023-10-17 05:23 UTC, Takuma-Ikeda commented on app/Models/Comment.php
> +        $replacedTexts = array();
PHP7 では配列を `= [];` で初期化することが多いです。

2023-10-17 05:53 UTC, ShutaTanaka commented
正規表現パターンを別サイトのものを参考にしたら、コメントに複数URLがあってもリンク化できた。
https://awesome-programmer.hateblo.jp/entry/2019/07/04/141315

正規表現の記載内容はあまり把握できていないが....

2023-10-17 06:00 UTC, Takuma-Ikeda requested changes

2023-10-17 06:00 UTC, Takuma-Ikeda commented on app/Models/Comment.php
> +                if (isset($matches[1])) {
この if 文は処理がないので不要じゃないですかね？
もし必要だったら return だけ書くとかして、次の a タグを生成する処理にいかないようにしないといけなさそうです。

2023-10-17 06:05 UTC, ShutaTanaka commented on app/Models/Comment.php
> +                if (isset($matches[1])) {
間違えて、if内を消してしまってました。
復元しました。

2023-10-17 07:39 UTC, ShutaTanaka commented
- リンク化処理のTextReplaceへの切り分け
- 複数箇所にリンク化処理の反映

ざっと見て回り、リンク化処理を反映させました。
ひとまず、このタスクは完了だと思ってます。

2023-10-17 07:42 UTC, ShutaTanaka commented
circleciのエラーが出ているので、調査します。

2023-10-17 07:43 UTC, Takuma-Ikeda requested changes

2023-10-17 07:43 UTC, Takuma-Ikeda commented on app/Helper/TextReplace.php
> +namespace App\Helper;
すみませんー、Laravel の命名規則的に `Helpers` に変更をお願いします。

2023-10-17 07:43 UTC, Takuma-Ikeda commented on app/Helper/TextReplace.php
> + * @param  string $value
null を渡す可能性があるなら `@param string|null $value` です

2023-10-17 07:43 UTC, Takuma-Ikeda commented on app/Helper/TextReplace.php
> +    {
`$value` が null だった場合の考慮がないですね。
特に何もせず、そのまま return でよいのではないでしょうか。

2023-10-17 07:43 UTC, Takuma-Ikeda commented on app/Models/Comment.php
> +use app\Helper\TextReplace;
大文字の App でお願いします！

2023-10-17 07:43 UTC, Takuma-Ikeda commented on composer.json
> +            "app/Helper/TextReplace.php"
これ必要でした？

2023-10-17 07:45 UTC, Takuma-Ikeda commented on app/Helper/TextReplace.php
> +    {
引数が null で渡される可能性があるということは、戻り値も null になる可能性があります。こちらの型も修正をお願いします。

2023-10-17 07:45 UTC, ShutaTanaka commented on composer.json
> +            "app/Helper/TextReplace.php"
こちら書かないと、クラスが読み込めなかったです。

2023-10-17 07:48 UTC, Takuma-Ikeda commented on composer.json
> +            "app/Helper/TextReplace.php"
小文字の app で use してるからとかないですか？

2023-10-17 07:56 UTC, Takuma-Ikeda commented
@ShutaTanaka 
次回からでよいのですが、コミットメッセージの書き方変更をお願いいたします。
GitHub ではコミットがこのように見えています↓

<img width="1307" alt="スクリーンショット 2023-10-17 16 54 43" src="https://github.com/EeeeG-Inc/OKR-web-app/assets/27577954/9b029b13-8858-4e8e-9048-799bee52949d">

このタイトルだと、どの修正がどのコミットに入っているのか探すのが大変になってしまいますので、
コミットごとに具体的なタイトルをつけてもらえると助かります！

2023-10-17 08:09 UTC, ShutaTanaka commented on composer.json
> +            "app/Helper/TextReplace.php"
承知しました。
削除して試してみます。

2023-10-17 08:12 UTC, ShutaTanaka commented on composer.json
> +            "app/Helper/TextReplace.php"
削除して`composer dump-autoload`した所、問題なく動きました。
プッシュし直します。

2023-10-17 08:15 UTC, Takuma-Ikeda requested changes

2023-10-17 08:15 UTC, Takuma-Ikeda commented on app/Helpers/TextReplace.php
> +        if(empty($value)){
empty() でも null 判定の条件を満たせるのですが、空文字とか 0 も true になってしまいます。
こういう null に限定されたシチュエーションでは `is_null()` を使って厳格に判定していただきたいです！

2023-10-17 08:15 UTC, Takuma-Ikeda commented on app/Helpers/TextReplace.php
> +            return null;
null を返却するという文脈では `return $value;` でも `return;` でも `return null;` でも結果は同じになります。
個人的には前者にして「受け取った引数に何も手を加えず返却してるよー」 と明示するほうが好みではあります。
ご参考までに。

2023-10-17 08:45 UTC, ShutaTanaka commented
指摘の修正完了しました。
タスク完了できてると思います。

2023-10-17 08:47 UTC, Takuma-Ikeda approved these changes
LGTM です！マージします！

2023-10-17 08:48 UTC, merged