コメントにいいねボタンを実装する
EeeeG-Inc/OKR-web-app pull request #161
Opened 2023-10-20 01:31 UTC by ShutaTanaka

# Issue

- #160

2023-10-20 01:44 UTC, Takuma-Ikeda requested changes

2023-10-20 01:44 UTC, Takuma-Ikeda commented on database/migrations/2023_10_19_180811_create_comment_like_user_table.php
> +        Schema::create('comment_like_user', function (Blueprint $table) {
すみません！Laravel のテーブル命名規則は複数形なので `comment_like_users` に変更をお願いいたします。
class 名もファイル名も変更が必要になります。

2023-10-20 01:44 UTC, Takuma-Ikeda commented on database/migrations/2023_10_19_180811_create_comment_like_user_table.php
> +            $table->id();
間違いではないのですが、他のマイグレーションファイルの書き方と合わせてもらえるとメンテしやすいです。

> $table->increments('id');

今回はこのようにお願いします。

2023-10-20 01:44 UTC, Takuma-Ikeda commented on database/migrations/2023_10_19_180811_create_comment_like_user_table.php
> +            $table->foreignId('user_id')->unsigned()->comment('ユーザID');
他のマイグレーションファイルでは最初にカラムの定義をして、それが終わってから外部キー設定をしています。

>  $table->foreign('user_id')->references('id')->on('users');

2023-10-20 01:44 UTC, Takuma-Ikeda commented on database/migrations/2023_10_19_180811_create_comment_like_user_table.php
> +            $table->timestamps();
どのコメントに対するいいねなのか分からないままになってるので `comment_id` の設定、外部キーの設定をお願いします。

2023-10-20 01:44 UTC, Takuma-Ikeda commented on database/migrations/2023_10_19_180811_create_comment_like_user_table.php
> +        Schema::dropIfExists('comment_like_user');
外部キー制約を先に消さないと、テーブルドロップに失敗することがありますので、先に下記を実行してください。

```php
Schema::table('comment_like_users', function (Blueprint $table): void {
    $table->dropForeign(['user_id', 'comment_id']);
});
```

2023-10-20 01:44 UTC, Takuma-Ikeda commented on database/migrations/2023_10_19_180811_create_comment_like_user_table.php
> +        Schema::dropIfExists('comment_like_user');
実際に `php artisan migrate` と `php artisan migrate:rollback --step=*` を交互に試して上手くいくか試してみてください。

2023-10-20 01:46 UTC, Takuma-Ikeda commented on database/migrations/2023_10_19_180811_create_comment_like_user_table.php
> +            $table->id();
あ、よくみたら `$table->id();` になってるマイグレーションファイルもありますね。これはいけませんね。。。
どちらでも大丈夫ということにしましょうw

2023-10-20 01:50 UTC, Takuma-Ikeda commented on database/migrations/2023_10_19_180811_create_comment_like_user_table.php
> +        Schema::dropIfExists('comment_like_user');
`step=*` の値は migrations テーブルか `php artisan migrate:status` の batch の数値をみればよいです。

2023-10-20 01:58 UTC, ShutaTanaka commented on database/migrations/2023_10_19_180811_create_comment_like_user_table.php
> +        Schema::create('comment_like_user', function (Blueprint $table) {
この変更はファイル名・クラス名を書き換えるのではなく、コマンドを叩き直しの方がよさそうでしょうか？

2023-10-20 02:08 UTC, Takuma-Ikeda commented on database/migrations/2023_10_19_180811_create_comment_like_user_table.php
> +        Schema::create('comment_like_user', function (Blueprint $table) {
直せるのであれば手動でもいいですが、
テーブル名・クラス名・ファイル名は紐づいているので、手動で直して間違うとマイグレーション実行時にエラーになる可能性があります

2023-10-20 02:12 UTC, Takuma-Ikeda requested changes

2023-10-20 02:12 UTC, Takuma-Ikeda commented on database/migrations/2023_10_19_180811_create_comment_like_user_table.php
> +            $table->foreignId('user_id')->unsigned()->comment('ユーザID');
すみません、追加で一点 `$table->integer('user_id')->unsigned()->comment('ユーザID');` でカラム追加が必要じゃないですかね？

2023-10-20 05:54 UTC, ShutaTanaka commented on database/migrations/2023_10_19_180811_create_comment_like_user_table.php
> +            $table->foreignId('user_id')->unsigned()->comment('ユーザID');
foreignIdでの書き方間違えてそうでした。
↓によるとカラム作成と外部キー設定をあわせた書き方のようでした。
https://qiita.com/Sunasuna24/items/469ef982c628f41e666f

しかし、池田さんにご指定いただいた書き方の方が明示的だと思いますので、カラム追加と外部キー設定を分けて両方書こうと思います。

2023-10-20 08:02 UTC, Takuma-Ikeda commented on database/migrations/2023_10_20_161214_create_comment_like_users_table.php
> +            ->references('id')
細かいですが、インデントをお願いいたします！

2023-10-20 08:06 UTC, Takuma-Ikeda requested changes

2023-10-20 08:06 UTC, Takuma-Ikeda commented on database/migrations/2023_10_20_161214_create_comment_like_users_table.php
> +            ->references('id')
細かいですが、インデントをお願いいたします！

2023-10-20 08:06 UTC, Takuma-Ikeda commented on database/migrations/2023_10_20_161214_create_comment_like_users_table.php
> +
user_id と comment_id の複合ユニーク制約を追加してください。
同じ組み合わせができることはないと思うので！

2023-10-20 08:44 UTC, Takuma-Ikeda requested changes

2023-10-20 08:44 UTC, Takuma-Ikeda commented on database/migrations/2023_10_20_161214_create_comment_like_users_table.php
> +            $table->dropUnique('comment_id_user_id_unique');
配列を渡せば、dropForeign と同じようにカラム指定できる気がします

2023-10-20 09:12 UTC, ShutaTanaka commented on database/migrations/2023_10_20_161214_create_comment_like_users_table.php
> +            $table->dropUnique('comment_id_user_id_unique');
$table->dropUnique('comment_id_user_id_unique');
↓
$table->dropUnique(['comment_id_user_id_unique']);
にする認識であってますでしょうか？

2023-10-20 09:25 UTC, Takuma-Ikeda commented on database/migrations/2023_10_20_161214_create_comment_like_users_table.php
> +            $table->dropUnique('comment_id_user_id_unique');
`$table->dropUnique(['comment_id', 'user_id']);` でいけませんかね？

2023-10-25 01:23 UTC, Takuma-Ikeda requested changes
途中だと思いますが、ざっと確認しました！

2023-10-25 01:23 UTC, Takuma-Ikeda commented on app/Models/CommentLikeUser.php
> +        /**
細かいですがコメントずれてますね。

2023-10-25 01:23 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +    public function __construct(CommentLikeUser $keyResult = null)
引数名が `$keyResult` になっています！

2023-10-25 01:23 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        $this->CommentLikeUser = $CommentLikeUser ?? new CommentLikeUser;
`$CommentLikeUser` ではなく `$commentLikeUser` でお願いいたします！
※ 頭文字が大文字になるのはクラス名だけです

あと別件ですが、`$CommentLikeUser` という変数がないってエラーは出ていますか？
※ `$keyResult` になっているからです
VS Code でエラー出てないようなら PHP のシンタックスチェックが入ってないと思われます。設定の確認をよろしくお願いします。PHP 案件ではマストといっていい設定なので恒久化していいと思います。

2023-10-25 01:23 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +    public function isLikedBy($comment,int $id): bool {
ここでの処理に必要なのは Comment モデルではなく、その id だけなので `int $commentId` で十分と思います。
モデルでとりあえずたくさんのデータを与えてしまうのはラクなんですが、必要最低限のデータを渡したほうが全体で何をしているのか・何のデータが必要なのかすっきりするからですね。

2023-10-25 01:23 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +    public function isLikedBy($comment,int $id): bool {
`int $id` だと CommentLikeUser の主キー id と誤読してしまう可能性があります。
ここでは `int $userId` でお願いします。

2023-10-25 01:23 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        return CommentLikeUser::where('comment_id', $comment->id)->where('is_like', TRUE )->where('user_id', $id )->first() !==null;
せっかくリポジトリを使ってインスタンス生成して単体テストできるようにしているので、モデルから static な呼び出しをするのではなく、
 
```sh
return $this->commentLikeUser
    ->where('comment_id', $commentId)
    ->where('is_like', TRUE )
    ->where('user_id', $id )
    ->exists();
```

で大丈夫です。コレクションの存在チェックは exists で可能です。

2023-10-25 01:23 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +    public function isLikedBy($comment,int $id): bool {
`{` の開始位置を一行下げてください。
これは Laravel のコーディング規約となります。

2023-10-25 01:23 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        return count(CommentLikeUser::where('comment_id', $comment->id)->where('is_like', TRUE )->get());
わざわざ count で全体をラップしなくても、コレクション型は便利メソッドが実装されています。
`->get()->count()` で十分と思います。

2023-10-25 01:23 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        return count(CommentLikeUser::where('comment_id', $comment->id)->where('is_like', TRUE )->get());
TRUE から true に変更をお願いします。
こちらの方が可読性が高く一般的だと思われますので🙇‍♂️

2023-10-25 01:23 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +    //ログインユーザーがイイねをしているいかを判定するメソッド。
コメントありがとうございます。
ただ、通常コメントだと関数をマウスオーバーしても Tips 表示してくれないので、PHP Doc で書いていただけるとありがたいです！

2023-10-25 01:23 UTC, Takuma-Ikeda commented on routes/web.php
> +    Route::post('/like', 'LikeController@like')->name('like');
基本的に `web.php` は画面のあるルーティングを書くので `api.php` に移動をお願いします。

2023-10-25 08:31 UTC, ShutaTanaka commented
ajax通信がかなり色々試したがうまく行かず、一旦プッシュした後にdockerの再起動を思い浮かびました。
試した所、うまくいきました。

2023-10-26 01:11 UTC, Takuma-Ikeda requested changes

2023-10-26 01:11 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
> +    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
CDN は header タグに埋め込まれたほうがいいですね。スクリプトの読み込み順があるので。
`@yield` と `@section` を使ってそうなるようにお願いいたします。

2023-10-26 01:11 UTC, Takuma-Ikeda commented on routes/api.php
> +Route::post('api/like', [LikeController::class, 'like'])->name('api/like');
`api/like` ではなく `/like/` で十分です。
`api.php` に定義されたルーティングは自動的に `api/` が付与されるからです。
たぶん今だと `api/api/like` になってる気がします。
artisan コマンドでルート確認してみてください。

2024-01-06 15:35 UTC, ShutaTanaka commented
### 残作業
- js部等のリファクタリング
- 指摘の対応

2024-02-06 06:41 UTC, Takuma-Ikeda requested changes
ちょっと見ました！

2024-02-06 06:41 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        return CommentLikeUser::where('comment_id', $comment_id)->where('is_like', true)->where('user_id', $id)->first() !==null;
null をイコールで比較するのは一般的ではないので is_null() を使いましょうか。
ですが、わざわざそんなことしなくても exitst() を使ってあげたほうがいいと思います。
Laravel が用意してくれているメソッドを積極的に使ってみてください！
https://qiita.com/miriwo/items/c4969adbe596dc36c7ea

2024-02-06 06:41 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        return CommentLikeUser::where('comment_id', $comment_id)->where('is_like', true)->where('user_id', $id)->first() !==null;
せっかくメンバ変数を定義しているので `$this->commentLikeUser` からクエリ実行してください！

2024-02-06 06:41 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        return CommentLikeUser::where('comment_id', $comment_id)->where('is_like', true)->get()->count();
ここもメンバ変数で！

2024-02-06 06:41 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        $like = CommentLikeUser::where('comment_id', $comment_id)
ここもメンバ変数で！

2024-02-06 06:41 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        return CommentLikeUser::where('comment_id', $comment_id)->where('is_like', true)->where('user_id', $id)->first() !==null;
where はメソッドチェーンしなくても、1 回で配列で 2 個以上の条件を渡せると思います！

2024-02-06 06:41 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        $like = CommentLikeUser::where('comment_id', $comment_id)
where はメソッドチェーンしなくても、1 回で配列で 2 個以上の条件を渡せると思います！

2024-02-06 06:41 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        return CommentLikeUser::where('comment_id', $comment_id)->where('is_like', true)->get()->count();
where はメソッドチェーンしなくても、1 回で配列で 2 個以上の条件を渡せると思います！

2024-02-06 06:41 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
> +                                                        @if (!$CommentLikeUser->isLikedBy($comment->id,Auth::id()))
あんまり Blade ファイル上でロジック実行したくないですね
Controller 側で処理したものを渡せませんか？

2024-02-06 08:47 UTC, Takuma-Ikeda reviewed
一点、確認です！

2024-02-06 08:47 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        ])
get() ということは Collection で取得していますが、
複数件のいいねレコードが存在する可能性があるということでしょうか。
そして複数件のレコードが存在する場合 `first()` で id の若い方を返すみたいな処理になってますが、そのロジックで合っているのでしょうか。

※ 1 ユーザー 1 コメントあたり最大 1 いいねなので、レコードは複数件になることはないと思っていました

2024-02-06 08:51 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        ])
https://readouble.com/laravel/10.x/ja/eloquent.html#retrieving-single-models
最大でも 1 レコードしか存在しないのであれば first で取得できますし、取得できなければ null が返ります。
慎重にやるなら firstOrFail で例外ハンドリングするのもありです

2024-02-06 09:14 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        ])
了解です！
間違って複数件登録されないように複合ユニーク制約もテーブル設定おねがいします！

2024-02-07 07:50 UTC, ShutaTanaka commented on app/Repositories/CommentLikeUserRepository.php
> +        ])
/OKR-web-app/database/migrations/2023_10_20_161214_create_comment_like_users_table.php

添付の記述で複合ユニーク制約できている認識なのですが、問題なさそうでしょうか？
![スクリーンショット 2024-02-07 16 48 47](https://github.com/EeeeG-Inc/OKR-web-app/assets/141220437/cb0fba8d-ba18-4e1f-84b2-f030117555f1)

2024-02-07 07:57 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        ])
大丈夫だと思います！

2024-02-08 09:18 UTC, Takuma-Ikeda requested changes

2024-02-08 09:18 UTC, Takuma-Ikeda commented on app/Models/CommentLikeUser.php
> +        return $this->hasMany(Comment::class, 'id');
https://readouble.com/laravel/10.x/ja/eloquent-relationships.html
リレーションは Laravel の重要な概念なので、上記ページで学んだほうがいいかもしれません。

ある CommentLikeUser を取得したとき、
ひとつの $commentLikeUser->user_id がとれるわけですが、
それを外部キーにして User テーブルから取得しようとしたら Many (複数) の User コレクションが取れるのでしょうか？

同様に、
ひとつの $commentLikeUser->comment_id がとれるわけですが、
それを外部キーにして Comment テーブルから取得しようとしたら  Many (複数) の Comment コレクションが取れるのでしょうか？

実際に `$commentLikeUser->users` や `$commentLikeUser->comments` をデバッグして、
どういう結果になるのか見たほうがいいとも思います。
※ ちなみに Many じゃなくて One のリレーションにするのであれば user や comment というメソッド名に修正してください。

もしくは BelongsTo が適切な場合もあります。しっかり考えてみてください。

2024-02-08 12:32 UTC, ShutaTanaka commented on app/Models/CommentLikeUser.php
> +        return $this->hasMany(Comment::class, 'id');
すみません。
リレーションだいぶ理解が低いままプッシュしてしまってました。
明日、学習後書き直します。

2024-02-14 08:14 UTC, ShutaTanaka commented on app/Models/CommentLikeUser.php
> +        return $this->hasMany(Comment::class, 'id');
【メモ】
- リレーション
  - テーブルの結合のようなもの。
  - 呼び出し方書き方を調べなければならない。
-  hasManyは結果が複数レコード文帰ってくる場合に使われるので、今回は違う。
  - 今回はcommentLikeUserテーブルのuser_idからusersテーブルの情報を引っ張ってくるので、１レコード分の情報しか取得対象にならない。
- 今回はhasOneかBelongsToを使用するのかと思われる。
  - どういった概念のものなのか、調べて理解が必要。
- 完成後、テスト用に呼び出しのコードを書いて、dd()で取得できているか検証する。

2024-02-14 08:47 UTC, Takuma-Ikeda requested changes

2024-02-14 08:47 UTC, Takuma-Ikeda commented on app/Http/Controllers/Api/LikeController.php
> +        return;
これは return 値が void になっていますね。
API にアクセスしても何も結果が返ってきていないことになります。
※ もちろん DB 更新はしていますが

フロントエンド側は Response 結果を知れたほうがいいと思うので、なにかしらの json を返してあげてください。

2024-02-14 08:47 UTC, Takuma-Ikeda commented on app/Http/Controllers/Api/LikeController.php
> +        return;
こちらも結果を返してください。

2024-02-14 08:47 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/LikeOperation.php
> +        $comment_id = $input['comment_id']; //コメントid
変数はキャメルケースで統一しているプロジェクトなので、修正をお願いします。
`//コメントid //操作者id` については、英単語の意味そのままなので特にコメントしなくていいかと思います。

2024-02-14 08:47 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/LikeOperation.php
> +        if($alreadyLike){
`if (オブジェクト)` は確かに true が返ってきますが、コンテキストが分かりにくいのでメソッドを使って判定してほしいです。
`if (is_null($alreadyLike))` でいいと思います。

2024-02-14 08:47 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/LikeOperation.php
> +        }else{
else を使うと if スコープが複雑になっていくので、書かない記述を推奨したいです。

```php
if (is_null($alreadyLike)) {
    return ...
}

return ...
```

うまく return を使ってください。

2024-02-14 08:47 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/LikeOperation.php
> +        }else{
細かいですが `if ()` や `} else {` など半角スペースを入れて欲しいです！
PSR-2準拠で！
https://qiita.com/speedstar18fct/items/c5966cb761596fc790bc

VS Code でアラート表示できるので設定をお願いします

2024-02-14 08:47 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/LikeOperation.php
> +        return;
この return は不要ですね。
void を返したいだけなら return 自体が不要。
ただ、このメソッドの実行結果くらいは return したほうがいいと思います。

2024-02-14 08:47 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/RemoveLikeOperation.php
> +        $comment_id = $input['comment_id']; //コメントid
変数名とコメントの修正をお願いします！

2024-02-14 08:47 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +    public function alreadyLike(int $comment_id, int $user_id): ?CommentLikeUser
`alreadyLike` というメソッド名だと、どういう結果が返ってくるのかわかりにくいですね。
`findByCommentIdAndUserId` とかだと、与える条件と find で Model が返ってくるのだなという印象になります。

あと、ちなみに Model を返す必要ってありますかね？
レコードが存在するかどうか bool で返すだけで良い気がします。
その場合だと exists() などを使えると思います。

2024-02-14 08:47 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +    public function likeCansel(CommentLikeUser $target): bool
cansel ではなく cancel のスペルミスかもです。
また、このメソッド名もどういう処理をしてくれるのかわかりにくいですね。
素直に `updateIsLike(CommentLikeUser $target, bool $isLike)` にして、引数の bool で UPDATE するって感じでよいかと。
※ false にしか変更できないのだと汎用性もないので

2024-02-14 08:47 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
> +                var likeId = document.getElementById("like");
ここだけ let じゃなくて var を使う理由はありますか。

2024-02-14 08:47 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
> +                userId = "{{Auth::user()->id}}";//ユーザーIdを取得
let を付けてほしいです！

2024-02-14 08:47 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
> +                    console.log('いいねキャンセル');
こちらはデバッグ用のコンソール出力だと思うので消しておいてください！

2024-02-14 08:47 UTC, Takuma-Ikeda commented on routes/api.php
> +Route::post('/remove', [LikeController::class, 'remove'])->name('remove');
エンドポイント見ただけだと、何を remove する API なのかわからないですね。
`like/remove` とか `like_remove` の方がいいですね。
name の修正、swagger 修正もお願いします。

2024-02-14 08:47 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
> +                //通信失敗した時の処理
全体的に JavaScript, PHP の基本文法レベルのコメントは削除してしまって大丈夫です。

https://www.e-xtreme.co.jp/topics/6698/#:~:text=%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88%E3%81%AB%E3%81%AF%E3%80%8C%E2%91%A0%E3%82%BD%E3%83%BC%E3%82%B9,%E3%81%84%E3%82%8B%E5%86%85%E5%AE%B9%E3%81%AF%E6%A7%98%E3%80%85%E3%81%A7%E3%81%99%E3%80%82

> 4.書かない方がいいコメントとは？
　悪いコメントは挙げたらキリが無いでしょうが、特にプログラマーが書いてしまいがちなのは、コメントを必要以上に長く書いてしまうことです。たとえば、「ソースコードをそのまま翻訳したコメント」は多くのプログラマーが書いてしまいます。これは、ソースコードを読めばわかることなので書く必要はありません。本来ソフトウェアは「コメント」ではなく「ソースコード」に書かれている通りに動作するので、プログラマーはソースコードを読んでプログラムを理解します。コメントに多くの情報を記載することは、反対に可読性を落としてしまうので、必要な情報に絞ることが効果的です。

2024-02-14 08:56 UTC, Takuma-Ikeda commented on app/Http/Controllers/Api/LikeController.php
> +        return;
```php
        $data = [
            'result' => $result,
        ];

        return new JsonResponse($data, Response::HTTP_OK);
```

こんな感じで返せます！

2024-02-14 09:00 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/LikeOperation.php
> +        if($alreadyLike){
https://www.php.net/manual/ja/types.comparisons.php

メソッド使わない場合の if 文の bool キャストは注意を払う必要があります。

2024-02-14 09:01 UTC, tenzyu commented on app/Http/Controllers/Api/LikeController.php
> +        return;
php は `function &test(): void {}` の `: void` みたいな書き方で返り値の型宣言ができるので、それぞれの API に`Response`(Illuminate\Http\Response) だとか `JsonResponse` だとかを与えてあげるといいかも

https://laravel.com/docs/10.x/responses

2024-02-14 09:11 UTC, tenzyu commented on resources/views/key_result/index.blade.php
> +                                                        @if (!$CommentLikeUser->isLikedBy($comment->id,Auth::id()))
https://laravel.com/docs/10.x/blade#displaying-data

2024-02-14 10:26 UTC, Takuma-Ikeda commented on app/Http/Controllers/Api/LikeController.php
> +    public function like(LikeRequest $request, LikeOperation $case)
戻り値の型を定義してください！

2024-02-14 10:38 UTC, Takuma-Ikeda commented on app/Http/UseCase/KeyResult/GetIndexData.php
> +            'CommentLikeUser' => $this->CommentLikeUserRepo,
`CommentLikeUser` 頭文字が大文字だと class name っぽいので、小文字にしておいてください！
あまり徹底できてなかったと思いますが、配列 key name はスネークケースだった気がします

2024-02-14 10:45 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +            'is_like' => true
絶対に is_like が true でしか UPDATE されないのは勘違いを生みやすいですね
`update` というメソッド名なのに is_like 以外のカラムは UPDATE できない実装なのも勘違いを生みやすい
これは予期せぬ「副作用」を生むので注意が必要です

もし is_like を true 決め打ちで UPDATE したいのであれば `updateIsLikeTrue()` にするべきかと
また引数の $target からメソッドを読んでますが、`$this->commentLikeUser` を使ってください

基本的には `update(array $input)` を作って、その配列データで UPDATE する処理を作れば十分かとは思いました

2024-02-14 10:47 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +    public function isLikedBy(int $comment_id, int $id): bool
引数の変数もキャメルケースでお願いします！

2024-02-15 06:15 UTC, Takuma-Ikeda requested changes

2024-02-15 06:15 UTC, Takuma-Ikeda commented on app/Models/CommentLikeUser.php
> +        return $this->belongsTo(Comment::class, 'comment_id');
BelongsTo は「逆」の関係性を意味するリレーションですが、
User.php や Comment.php には「逆」の反対のリレーションが既に定義付けされているということでしょうか。

2024-02-15 06:24 UTC, Takuma-Ikeda requested changes

2024-02-15 06:24 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/LikeOperation.php
> +            Flash::error($exc->getMessage());
Exception のエラーメッセージは技術者向けの内容になります。
それをアプリの画面に表示するかどうかは時と場合によりますが、
一般的には平易な内容であることが多いです

「いいね処理中に失敗しました」とか...ですかね
多言語ファイルにそういうエラーメッセージを定義して表示するイメージです

なお、この try-catch で Exception が発生することってありえますかね？
外部連携しているわけではないので、シンタックスエラーか二重登録でユニーク制約に引っかかるくらいしかないような気がします

また、API 処理中に Blade の Flash メッセージって設定・表示できましたっけ
API 呼び出し直後はフロントエンドは画面更新されていないので、画面にエラーメッセージ表示されないような...
※ ブラウザリロードしたら表示されるかもですが、表示タイミングは不適切な気がします

2024-02-15 06:31 UTC, ShutaTanaka commented on app/Models/CommentLikeUser.php
> +        return $this->belongsTo(Comment::class, 'comment_id');
User.php や Comment.phpにはCommentLikeUser.phpへのリレーションはないです。

CommentLikeUser.phpをhasOneに書き直すか、User.php や Comment.php には「逆」の反対のリレーションを追加しなければならないかと思います。
この場合どちらの対応が正しいでしょうか？

User.php や Comment.php には「逆」の反対のリレーションは使い所がなさそうなので、CommentLikeUser.phpをhasOneに書き直すでいいかとは思ってます。

2024-02-15 06:34 UTC, ShutaTanaka commented on app/Http/UseCase/Api/Like/LikeOperation.php
> +            Flash::error($exc->getMessage());
ここで、Exception が発生することはないかと思います。
DB更新処理後に「return true」でtrueを返すだけに書き換えようと思います。

2024-02-15 06:37 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/LikeOperation.php
> +            Flash::error($exc->getMessage());
[補足[
API の Exception のエラーメッセージは画面メッセージというより、デバッグする用にログとして保存してほしいです。

2024-02-15 06:46 UTC, Takuma-Ikeda commented on app/Models/CommentLikeUser.php
> +        return $this->belongsTo(Comment::class, 'comment_id');
BelongsTo そのものは「逆」しか意味しないので
それだけしかないとソースコードから「1対1」なのか「1対多」のどちらなのか読み取れません

> リレーションは使い所がなさそう

使い所が現状なくても、BelongsTo を使うのであれば明示してほしいところです。

HasMany - HasOne or HasMany - BelongsTo
HasOne - HasOne or HasOne - BelongsTo

すでにお気づきかもしれませんが、BelongsTo は HasOne の代わりにしかなりません。
だからリレーション先が「Many」か「One」か特定できないのです。

2024-02-15 06:54 UTC, ShutaTanaka commented on app/Models/CommentLikeUser.php
> +        return $this->belongsTo(Comment::class, 'comment_id');
承知しました。
CommentLikeUser.phpにはBelongsToで書いて、
User.php や Comment.php には「逆」の反対のリレーションをhasManyで書こうと思います。

2024-02-19 08:04 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        return CommentLikeUser::where('comment_id', $comment_id)->where('is_like', true)->where('user_id', $id)->first() !==null;
```suggestion
        $commentLikeUser = $this->commentLikeUserRepo::where('comment_id', $comment_id)
            ->where('is_like', true)
            ->where('user_id', $id)
            ->first();
            
             return !is_null($commentLikeUser)
```

- 読みやすさ重視で改行を入れてほしい
- null は !== 比較しない
- メンバ変数の repo から実行してほしい (モデルのファサードは使わない)
- できれば where 条件は配列でまとめてほしい

2024-02-19 10:22 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
> +    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
https://github.com/EeeeG-Inc/OKR-web-app/blob/main/resources/views/layouts/app.blade.php#L155
こちら、すでに app.blade.php で読み込んでいるみたいですが
index.blade.php で再度読み込む必要ってありましたか？

2024-02-20 09:41 UTC, Takuma-Ikeda requested changes

2024-02-20 09:41 UTC, Takuma-Ikeda commented on resources/views/layouts/app.blade.php
> -{{-- <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> --}}
このへん jQuery 使ってると思うので動作確認おねがいします！

<img width="629" alt="スクリーンショット 2024-02-20 18 33 36" src="https://github.com/EeeeG-Inc/OKR-web-app/assets/27577954/8d689685-2da0-48b5-b9f1-5906277a4ed5">

2024-02-20 09:41 UTC, Takuma-Ikeda commented on resources/views/layouts/app.blade.php
> +    @stack('scripts')
すでに `@stack('scripts')` が 150 行目あたりにあるので同名のものは避けてほしいところです！

2024-02-20 09:41 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
> +    <script>
他ファイルの jQuery ロジック同様、ここのロジック全体を `scripts` にプッシュできませんか？

2024-02-20 09:49 UTC, tenzyu commented on resources/views/layouts/app.blade.php
> +    @stack('scripts')
個人的に選びそうな解決法
1. head の方を cdn 限定の扱いにして `@stack('cdn')` にする
2. 150行目を消す
3. `@stack('scripts-head')` のようにして、head で読みたいものだけ `scripts-head` に push, そうでないものは `scripts` に push するように使い分ける

自分はたぶん 3 を選ぶ

2024-02-21 07:41 UTC, Takuma-Ikeda requested changes

2024-02-21 07:41 UTC, Takuma-Ikeda commented on resources/views/quarter/edit.blade.php
> +        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
`<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>`
他と同様これでいい気がします

2024-02-22 09:15 UTC, ShutaTanaka commented
cdnをbladeで複数書いてしまっているので、incluedを使ってまとめる。


参考
https://zenn.dev/ytksato/articles/2a1c5352473723
https://github.com/yobutamejp/yobutame-backend/blob/main/resources/views/parts/google_analytics.blade.php
https://github.com/search?q=repo%3Ayobutamejp%2Fyobutame-backend%20google_analytics&type=code

- partディレクトリを作ってそこにcdnを書く。

2024-02-27 01:48 UTC, Takuma-Ikeda requested changes

2024-02-27 01:48 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        $model = $this->commentLikeUser->findOrFail($id);
https://qiita.com/moutoonm342/items/995f11de4275b43d7f4c
`findOrFail` を使っていますが、これは Fail になって Exception に倒れることはありますか？
すでに存在している Model の id を引数に渡しているので、必ず find できる気がします。

2024-02-27 01:48 UTC, Takuma-Ikeda commented on app/Repositories/CommentLikeUserRepository.php
> +        $model = $this->commentLikeUser->findOrFail($id);
変数名 `$model` だと抽象的すぎるので、具体的に `$commentLikeUser` としてくれると嬉しいです。

2024-02-27 01:48 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/LikeOperation.php
> +        $this->CommentLikeUserRepo->update($findByCommentIdAndUserId->id, $data);
変数 `$data` はここで一回しか使ってないので、わざわざ変数定義しなくていいと思います。
※ 変数定義していると 2 回以上どこかで使われているのかな？とエンジニアが考えてしまうためです

2024-02-27 01:48 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/RemoveLikeOperation.php
> +        $this->CommentLikeUserRepo->update($findByCommentIdAndUserId->id, $data);
この $data もよろしくお願いします。

2024-02-27 11:10 UTC, ShutaTanaka commented
## 不具合発覚
- コメントが複数存在している時、以下がうまく動いていない。
  - いいねのカウント増減表示
  - いいねボタンの活性非活性
![スクリーンショット 2024-02-27 20 05 31](https://github.com/EeeeG-Inc/OKR-web-app/assets/141220437/70ef25c3-c8a3-407f-b285-bf2bf542ac90)

2024-02-27 22:57 UTC, Takuma-Ikeda requested changes

2024-02-27 22:57 UTC, Takuma-Ikeda commented on app/Http/UseCase/KeyResult/GetIndexData.php
> +            $comments[$key]->isLiked = $this->commentLikeUserRepo->isLikedBy($comment->id, auth()->id());
https://github.com/EeeeG-Inc/OKR-web-app/blob/feature/comment-make-like-button/app/Models/Comment.php#L68

本来 Comment モデルには liceCount や isLiked といった attributes は存在してないですし、
comments テーブルにそういったカラムも存在していなかったと思います。

つまりここでやっているのは、この場限定で Comment モデルにグローバルな変数を持たせているということです。
動いているとは思いますが、
この場限定の処理なので、他のエンジニアは勘違いを生みやすいかと思います。

View で `$comment->isLiked` してたり、
Controller で dd したら `$comment->isLiked` なるものが見えるので、
なるほど、このモデルはそういう attribute が備わっているのだな、という勘違いですね

個人的には少し気持ち悪い実装なので、
モデルに getAttribure メソッドを実装して存在を明示的にしてもらうか、
まったく別の変数を用意して View に渡すか、がいいと思います ※ わざわざ Comment モデルに値を設定している理由もないと思いますので

2024-02-27 23:01 UTC, Takuma-Ikeda commented on app/Http/UseCase/KeyResult/GetIndexData.php
> +            $comments[$key]->isLiked = $this->commentLikeUserRepo->isLikedBy($comment->id, auth()->id());
```php
foreach ($comments as $key => $comment) {
            $comments[$key]->isLiked 
```

ちなみにここですが、
せっかく `$comment` で要素を取り出しているのだから
わざわざ  `$comments[$key]` で指定する必要ないかと思います。

```suggestion
        foreach ($comments as $comment) {
            $comment->isLiked = $this->commentLikeUserRepo->isLikedBy($comment->id, auth()->id());
```

この処理だったら `$key` 自体がそもそも不要ですね

2024-02-27 23:54 UTC, Takuma-Ikeda commented
> コメントが複数存在している時、以下がうまく動いていない。
いいねのカウント増減表示
いいねボタンの活性非活性

ちゃんとソースコード追ってないですけど
JavaScript の問題っぽいのと
HTML の class 名, id 名が重複しているので、JS がどのボタンの操作かわからん〜ってエラー吐いてる気がする
console 見てあげてください

2024-03-01 08:26 UTC, Takuma-Ikeda requested changes
とりあえず最新コミットの内容だけ見ました！

2024-03-01 08:26 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
> +                                                            <span class="like-counter">{{$commentLikeUserInfo[$comment->id]['likeCount']}}</span>
`<span class="like-counter">{{$commentLikeUserInfo[$comment->id]['likeCount']}}</span>`

これは if だろうと else だろうと同じ表示なので、
条件分岐処理に含める必要がなさそうです。

2024-03-01 08:26 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
> +                                                            <i class="fas fa-music heart like-toggle liked" data-comment-id="{{ $comment->id }}" data-like-remove= "ture"></i>
> data-like-remove= "ture"

typo でしょうか？

2024-03-01 08:26 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
>                          console.log('いいねキャンセル');
console.log する必要なさそうです
フロントエンドで console.log してしまうと、一般ユーザーからデバッグ情報が見えてしまうので基本的に開発時以外はやらないほうがいいと思います

2024-03-01 08:26 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
> +                    } else {
ここも if - else 使う必要ないですね
っていうか else は絶対使わないくらいの感じでいいと思います
結果を return する関数を用意するようにすれば else スコープは不要になりますし、
関数として処理を切り出すことで何をやっているのか分かりやすくなります

2024-03-01 08:45 UTC, Takuma-Ikeda requested changes
ちょっと他の差分が多く混じっているのでそれっぽいとこしか見れてないですが、一応レビューしました！

2024-03-01 08:45 UTC, Takuma-Ikeda commented on app/Http/Controllers/Api/LikeController.php
> +        return new JsonResponse([
今回 `$result` は true しか返してないと思いますが、
今後 false が返ってくる場合 のことも想定して、
`HTTP_INTERNAL_SERVER_ERROR` あたりを返す Json も返したほうがいいかもです。

2024-03-01 08:45 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/LikeOperation.php
> +        $findByCommentIdAndUserId = $this->CommentLikeUserRepo->findByCommentIdAndUserId($commentId, $userId);
変数名は `$commentLikeUser` (モデルの型) でいいと思います。
今は関数名になっていますので、どんなデータが入っているのかちょっと想像できないです。

2024-03-01 08:45 UTC, Takuma-Ikeda commented on app/Http/UseCase/Api/Like/RemoveLikeOperation.php
> +        $findByCommentIdAndUserId = $this->CommentLikeUserRepo->findByCommentIdAndUserId($commentId, $userId);
ここの変数名も修正してください。

2024-03-01 08:47 UTC, Takuma-Ikeda commented on app/Http/Controllers/Api/LikeController.php
> +        return new JsonResponse([
となると 500 エラーを返す可能性がある
っていう swagger の定義も必要です

2024-03-05 00:03 UTC, Takuma-Ikeda requested changes

2024-03-05 00:03 UTC, Takuma-Ikeda commented on resources/views/key_result/index.blade.php
> +                    function cancelLike() {
この指摘も細かいですが、
cancel なのか remove なのか、使う英単語は統一したいところです！
もっと大きい規模のプロジェクトだと、たくさんいるエンジニアがそれぞれ適当にメソッド名を決めてしまうと収集がつかなくなってしまうんですよね...

2024-03-05 06:59 UTC, Takuma-Ikeda commented
@ShutaTanaka 
今回のように UI が変更される場合、概要欄にスクリーンショットを貼ってほしいです！
よろしくお願いします。

2024-03-05 07:12 UTC, ShutaTanaka commented
![スクリーンショット 2024-03-05 16 09 46](https://github.com/EeeeG-Inc/OKR-web-app/assets/141220437/b68ffdfe-87a4-4fec-a1f9-4428e58824d8)
ajax通信エラー発生の画面です。
テストコメント２のいいねボタン押下時です。

エラーが発生したコメントの横に、赤字でエラーメッセージが表示されるようにしてます。

2024-03-05 09:04 UTC, Takuma-Ikeda approved these changes
LGTM です！！
長期間の対応お疲れ様でした！

2024-03-05 09:05 UTC, merged